"""给admin表添加id列

Revision ID: e4051f2f5a06
Revises: 
Create Date: 2023-05-07 13:40:25.618073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4051f2f5a06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        
        # batch_op.create_unique_constraint(None, ['id'])
    connection = op.get_bind()
    batch_op.execute("UPDATE admin SET id = 1 WHERE name = 'admin'")
    batch_op.execute("UPDATE admin SET id = 2 WHERE name = 'john'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
